name: "Hello"

on:
  pull_request:
    types: [opened, reopened]
   
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - name: Get changes
        id: changed-files
        run: git diff --name-only -r HEAD^1 HEAD >> "$GITHUB_OUTPUT"
      - name: Run action
        uses: ./
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs }}
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: 'needs-review'
          files: ${{ ALL_CHANGED_FILES }}
