name: "Hello"

on:
  pull_request:
    types: [opened, reopened]
   
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
      - uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          label: 'needs-review'
          files: $(git diff --name-only HEAD^)
